Add MySQL 8, Ubuntu 20.04 and EL8 support
sous-chefs/mysql pull request #653
Opened 2020-11-19 22:45 UTC by EMH333

## Currently a draft so I can make sure tests are passing, also still need to update readme and changelog

## Description

- Adds support for MySQL 8
- Adds support for Ubuntu 20.04
- Adds support for CentOS 8

Also removes EL6 and Ubuntu 14.04 both of which are EOL/close to EOL

### Issues Resolved

Related to #611 

This also is a prerequisite for #522 (for which I will have another PR very soon)

### Check List
- [ ] All tests pass. See https://github.com/sous-chefs/mysql/blob/master/TESTING.md
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

2020-11-19 22:48 UTC, kitchen-porter commented
<!--
  1 Error: Please include a CHANGELOG ent...
  0 Warnings
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-11-23 18:16 UTC, Xorima commented
Hey @EMH333 

This is awesome!

Can you get something added to the changelog as well please though

Thanks!

2020-11-24 01:00 UTC, EMH333 commented
Done!

2020-11-24 16:31 UTC, ramereth requested changes
Can you also add support for checking Debian 10 and remove support for Debian 8 while you're at it? Great work thus far!

2020-11-24 16:31 UTC, ramereth commented on libraries/helpers.rb
>        return '5.5' if trusty?
This should be removed since you removed support for both 5.5 and 14.04. You should also remove the helper.

2020-11-24 17:31 UTC, Xorima commented
Can we also have documented the versions of mysql that get removed by this pr in the changelog, just so no one is caught by surprise :)

2020-11-25 02:21 UTC, ramereth requested changes

2020-11-25 02:21 UTC, ramereth commented on README.md
> +| ubuntu-20.04   |     |     |  X  |
Please update the list to include Debian support. Also alphabetize it.

2020-11-25 02:21 UTC, ramereth commented on kitchen.dokken.yml
> +        - RUN /usr/bin/apt-get update
Please remove debian-8 above here.

2020-11-25 19:45 UTC, Xorima approved these changes

2020-11-27 18:42 UTC, merged

2020-11-27 18:42 UTC, kitchen-porter commented
Released as: [9.0.0](https://github.com/sous-chefs/mysql/releases/tag/9.0.0)