Update README.md
sous-chefs/mysql pull request #659
Opened 2021-02-02 11:17 UTC by axos88-da

update cookbook version in readme.md

2021-02-02 23:47 UTC, ramereth reviewed
Can you also remove Ubuntu 16.04 in the readme as we removed it in #655 and was missed?

2021-02-02 23:47 UTC, ramereth commented on README.md
> +depends 'mysql', '~> 10.0'
It might make more sense to not have the version pinned here so we don't have to keep updating it.
```suggestion
depends 'mysql'
```

2021-02-03 09:22 UTC, axos88-da commented
Done

2021-02-03 17:27 UTC, ramereth commented
@axos88-da can you please add a changelog entry?

2021-02-04 13:57 UTC, axos88-da commented
For changing the README.md file?

2021-02-04 15:55 UTC, ramereth commented
@axos88-da yeah, we need something in the changelog for our automatic release system to work properly.

2021-02-08 19:11 UTC, ramereth requested changes

2021-02-08 19:11 UTC, ramereth commented on CHANGELOG.md
>  ## Unreleased
This needs to have a newline.

2021-02-09 14:12 UTC, axos88-da commented
Never mind.

2021-02-25 00:37 UTC, merged

2021-02-25 00:37 UTC, kitchen-porter commented
Released as: [10.0.2](https://github.com/sous-chefs/mysql/releases/tag/10.0.2)